### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by bmoren** [bmoren/p5js-cheat-sheet#10]
Looking for help on this!

**Comment by maxdevjs** [comment]
I can help with Portuguese. Italian too, if needed.

**Comment by bmoren** [comment]
These would both be amazing. 

there are 2 ways to handle the translation depending on your familiarity with HTML & Git. 

## 1
If you're not comfortable with HTML & GIT, then please respond to this issue with the translations for each section and I will implement and confirm them with you before pushing them live!

## 2
If you are comfortable with HTML & making git pull requests, then please:
+ clone the repository
+ navigate to the `docs` folder
+ copy `index.html` & rename to `pt.html`
+ make all translation changes inside of the  `<code class="language-javaScript"></code>` tags
+ make all translation changes to the `terms` JSON object at the bottom of the HTML page. 
+ add your name as the translator + link in the `<footer>`
+ make a pull request against the repository

## bonus tasks (if you have time or are able)
### update the readme:
+ add your name as the translator + link to the readme.md
+ add a link to the new translation in the readme.md

### update the menu:
+ in the `docs` folder, find the `menu.js` file and add a link to the translation page

### add a pdf:
+ export a pdf and add to the root (print to PDF in chrome), please name it `p5cheatsheet-PT.pdf`
+ verify that it will all fit on one page, if there is overflow, some minor custom CSS may need to be implemented.
