### ISSUE TITLE
should the == in the if/then be a ===

### ISSUE THREAD

**Issue by bmoren** [bmoren/p5js-cheat-sheet#23]
as per this twitter thread: 

https://twitter.com/OtherMichael/status/1200162299358699520

**Comment by bmoren** [comment]
p5.js reference uses triple:

https://p5js.org/reference/#/p5/===

**Comment by MichaelPaulukonis** [comment]
The double-equals is one of those JavaScript "mistakes" that are best forgotten and avoided. They lead to subtle bugs and frustrations. If new coders are never taught the double-equals, they will never have to worry about it's weird coercion rules. 

While JavaScript "best practices" can be argued in many cases, double-equals is pretty universally considered a be "bad thing" and should not appear in p5js examples and documentation.

Now, if we could all agree to use Instance mode in all cases, even better!

**Comment by maxdevjs** [comment]
If, as a first DAY programmer, I can not see it (the `==`), it does not even exist for me (and, consequently, its nuances), making things easier at the beginning. If I start seeing a `===` I can ask why not `==`, but still would be implied that the triple equals is the way to go.

Using it (the `==`) in the cheat-sheet, at a certain point, it could be also needed to explain why to avoid it, making room for more doubts than certainties.

At least, my point of view :)

**Comment by bmoren** [comment]
This all makes sense to me! Thanks for the thoughts.

Lets implement this change. I'll get to it later in the week, but if anyone wants to make a PR with the fixes earlier I'm happy to merge. It will require a re-export of all of the PDF files as well (print to PDF from chrome until #24 can get sorted out).

**Comment by bmoren** [comment]
this is now in place in the web based versions and will become part of the pdfs when the build process is in place
