### ISSUE TITLE
Printer icon does not print when clicked

### ISSUE THREAD

**Issue by joh-nah** [bmoren/p5js-cheat-sheet#34]
Based off the assumption that the user is to click the printer icon to print the cheatsheet, nothing happens when it is clicked.

Browsers tried: Firefox, Chrome & Safari
Language: English

**Comment by bmoren** [comment]
I think this is a scoping issue, the printing works for me if I first change language using the dropdown, but not on the initial load of the page.

**Comment by trikaphundo** [comment]
I think I have spotted the error. Let me make a few tests and will file a PR with the fix.
