### ISSUE TITLE
FR French version of the indd file is ready

### ISSUE THREAD

**Issue by rich-gg** [bmoren/p5js-cheat-sheet#4]
how do I upload it ?

:)

**Comment by bmoren** [comment]
These articles should give you want you need to know~

Please organize the files in a logical manner!

https://help.github.com/en/articles/fork-a-repo
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

& most importantly, thank you your doing the translation!

**Comment by bmoren** [comment]
Also, let me know if this is too cumbersome to figure out and I'm happy to get the files from you in other ways and add them to the repository! (I totally understand that git can be like trying to walk through a brick wall of obscurity the first times contributing to a repository – I still often feel like I'm just trying my best not to break something!)

**Comment by rich-gg** [comment]
really nice of you to understand that

I spent my week figuring out Nagios and snmp tricks so when comes the week end...

here you go
http://rich.gg/files/p5cheatsheet-FR.indd

cheers
